sensors:
  - dabai_dc1_pointcloud

dabai_dc1_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /camera/depth/points
  max_range: 2.0
  point_subsample: 8
  padding_offset: 0.02
  padding_scale: 1.0
  max_update_rate: 10.0
  filtered_cloud_topic: /moveit/filtered_cloud
